version: 2.1

commands:
  build:
    description: "Compile, run tests and run static analysis"
    parameters:
      flag:
        type: string
        default: ""
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: java -version
      - run: ./mvnw -B --no-transfer-progress clean verify << parameters.flag >>
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.m2

jobs:
  jdk8:
    docker:
      - image: openjdk:8-jdk
    steps:
      - build
  jdk11:
    docker:
      - image: openjdk:11-jdk
    steps:
      - build
  jdk14:
    docker:
      - image: openjdk:14-jdk
    steps:
      - build
  jdk-ea-experimental:
    docker:
      - image: openjdk:15-jdk
    steps:
      - build:
          flag: -Dexperimental
  jdk-ea-full:
    docker:
      - image: openjdk:15-jdk
    steps:
      - build

workflows:
  version: 2.1
  on_push:
    jobs:
      - jdk8
      - jdk11
      - jdk14
  weekly-experimental:
    triggers:
      - schedule:
          cron: "0 2 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - jdk-ea-experimental
      - jdk-ea-full
  weekly-regression:
    triggers:
      - schedule:
          cron: "30 2 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - jdk8
      - jdk11
      - jdk14
